  $( function() {
    var projects = [
{value: "https://meet.google.com/miw-prqc-rfz", label: "Aboal Claudia", desc: "Aboal Claudia",},
{value: "https://meet.google.com/qha-eyaa-gwv", label: "Acerra Patricia", desc: "Acerra Patricia",},
{value: "https://meet.google.com/wvj-cksr-pwk", label: "Acosta Guillermo", desc: "Acosta Guillermo",},
{value: "https://meet.google.com/rrv-tzzu-yrp", label: "Adragna Claudio", desc: "Adragna Claudio",},
{value: "https://meet.google.com/rnq-kvja-wnj", label: "Agueira Diego", desc: "Agueira Diego",},
{value: "https://meet.google.com/ajy-ekre-qmq", label: "Albin Ruben", desc: "Albin Ruben",},
{value: "https://meet.google.com/ybo-ogsn-pux", label: "Alcaraz Cesar", desc: "Alcaraz Cesar",},
{value: "https://meet.google.com/pyf-vabb-eui", label: "Almaraz Adrian", desc: "Almaraz Adrian",},
{value: "https://meet.google.com/iat-xbev-jnx", label: "Altamira Laura", desc: "Altamira Laura",},
{value: "https://meet.google.com/ocj-zprx-bpk", label: "Aluma Verónica", desc: "Aluma Verónica",},
{value: "https://meet.google.com/stj-ppzm-thm", label: "Ammirati Claudio", desc: "Ammirati Claudio",},
{value: "https://meet.google.com/htw-ovgj-ekw", label: "Andre Fabricio", desc: "Andre Fabricio",},
{value: "https://meet.google.com/cyd-rxbm-hcf", label: "Araujo Raúl", desc: "Araujo Raúl",},
{value: "https://meet.google.com/ips-fhyn-mzf", label: "Arce Cristian Pablo", desc: "Arce Cristian Pablo",},
{value: "https://meet.google.com/xjq-odag-vey", label: "Arida Lucila", desc: "Arida Lucila",},
{value: "https://meet.google.com/ejx-swtw-tif", label: "Arraez Maria Sol", desc: "Arraez Maria Sol",},
{value: "https://meet.google.com/ghz-hznq-biz", label: "Arschinov César", desc: "Arschinov César",},
{value: "https://meet.google.com/vih-jvkd-fib", label: "Avalos Eduardo", desc: "Avalos Eduardo",},
{value: "https://meet.google.com/xeh-ntod-dgp", label: "Bado Orlando", desc: "Bado Orlando",},
{value: "https://meet.google.com/qov-uhis-ive", label: "Bahamodez Nicolas", desc: "Bahamodez Nicolas",},
{value: "https://meet.google.com/zqi-rwbw-ipp", label: "Barbieri Marcelo", desc: "Barbieri Marcelo",},
{value: "https://meet.google.com/hnb-owau-spx", label: "Bausilio Vicente", desc: "Bausilio Vicente",},
{value: "https://meet.google.com/fce-igqo-cdy", label: "Baylac Maria", desc: "Baylac Maria",},
{value: "https://meet.google.com/izv-miwf-ygg", label: "Borodowski Fernando", desc: "Borodowski Fernando",},
{value: "https://meet.google.com/yjk-xdym-vdi", label: "Bozzini Andrea", desc: "Bozzini Andrea",},
{value: "https://meet.google.com/pzo-pure-wos", label: "Bringas Cristina", desc: "Bringas Cristina",},
{value: "https://meet.google.com/zzp-sagc-ybw", label: "Bruno Cecilia", desc: "Bruno Cecilia",},
{value: "https://meet.google.com/vbz-omyi-kgv", label: "Buchmuller Carlos", desc: "Buchmuller Carlos",},
{value: "https://meet.google.com/beo-jssv-hwu", label: "Buffoni, Antonella Maria", desc: "Buffoni, Antonella Maria",},
{value: "https://meet.google.com/jjx-byoq-vmi", label: "Busato Paola", desc: "Busato Paola",},
{value: "https://meet.google.com/cmv-tdmc-sqw", label: "Bustos Gaston Miguel", desc: "Bustos Gaston Miguel",},
{value: "https://meet.google.com/yqp-uehm-cfe", label: "Camara Patricia", desc: "Camara Patricia",},
{value: "meet.google.com/yqb-ywgb-kag", label: "Camargo Mauricio", desc: "Camargo Mauricio",},
{value: "https://meet.google.com/oyg-ajct-pjv", label: "Campos José Evaristo", desc: "Campos José Evaristo",},
{value: "https://meet.google.com/rbo-dwgv-ugz", label: "Cantera Juan Pablo", desc: "Cantera Juan Pablo",},
{value: "https://meet.google.com/zgb-jheq-mea", label: "Canteros Víctor", desc: "Canteros Víctor",},
{value: "https://meet.google.com/dsz-otwc-peu", label: "Capolungo Roberto", desc: "Capolungo Roberto",},
{value: "meet.google.com/uwz-vpwj-naq", label: "Capriotti Pablo", desc: "Capriotti Pablo",},
{value: "https://meet.google.com/jum-rufv-iyx", label: "Carabelli Lia Gabriela", desc: "Carabelli Lia Gabriela",},
{value: "https://meet.google.com/mad-jkgt-tnh", label: "Carassai Matias Alfredo", desc: "Carassai Matias Alfredo",},
{value: "https://meet.google.com/dwe-mdsz-nmu", label: "Cardonetti Juan Carlos", desc: "Cardonetti Juan Carlos",},
{value: "https://meet.google.com/ewn-ophg-gqi", label: "Carusso Dante Gabriel", desc: "Carusso Dante Gabriel",},
{value: "https://meet.google.com/txj-topr-ece", label: "Castro Cau Julia Carlos Silvestre", desc: "Castro Cau Julia Carlos Silvestre",},
{value: "https://meet.google.com/rhy-vuun-fhu", label: "Castro, Mariana Mercedes", desc: "Castro, Mariana Mercedes",},
{value: "https://meet.google.com/qyh-vbhv-oyb", label: "Caviglia Mariano", desc: "Caviglia Mariano",},
{value: "https://meet.google.com/pjb-iyny-jdz", label: "Cedro Viviana", desc: "Cedro Viviana",},
{value: "https://meet.google.com/xsx-yrzk-wby", label: "Cerviño Marcelo", desc: "Cerviño Marcelo",},
{value: "https://meet.google.com/son-gxwx-pvh", label: "Chamorro Jorge", desc: "Chamorro Jorge",},
{value: "https://meet.google.com/pzp-ybuc-gkt", label: "Ciappino Alejandro", desc: "Ciappino Alejandro",},
{value: "https://meet.google.com/mha-ncuy-aoa", label: "Clos Federico", desc: "Clos Federico",},
{value: "https://meet.google.com/bmm-fitj-hfx", label: "Colombo Gustavo", desc: "Colombo Gustavo",},
{value: "https://meet.google.com/zcj-ajjv-pbq", label: "Cordoba Juan Manuel", desc: "Cordoba Juan Manuel",},
{value: "https://meet.google.com/jvr-ppfo-ffk", label: "Corigliano Antonio", desc: "Corigliano Antonio",},
{value: "https://meet.google.com/dsg-nfuy-wdi", label: "Corniglione Rivero  J.", desc: "Corniglione Rivero  J.",},
{value: "https://meet.google.com/zqg-abkr-urz", label: "Coronato Jerónimo", desc: "Coronato Jerónimo",},
{value: "https://meet.google.com/zce-vtad-izk", label: "Correa Guillermo", desc: "Correa Guillermo",},
{value: "https://meet.google.com/qjy-bgpr-htf", label: "Cortese Silvina", desc: "Cortese Silvina",},
{value: "https://meet.google.com/ocp-moqm-opw", label: "Couso Alejandro", desc: "Couso Alejandro",},
{value: "https://meet.google.com/nju-xqkz-udj", label: "Couso Sergio", desc: "Couso Sergio",},
{value: "https://meet.google.com/wmv-nmii-wmm", label: "Crotti Alejandra", desc: "Crotti Alejandra",},
{value: "https://meet.google.com/jpy-fgkk-eon", label: "Cruzate Edgardo", desc: "Cruzate Edgardo",},
{value: "https://meet.google.com/zcs-rmcd-tjg", label: "Da Prá Javier Eduardo", desc: "Da Prá Javier Eduardo",},
{value: "https://meet.google.com/syn-tqjd-fim", label: "Daher Sergio", desc: "Daher Sergio",},
{value: "https://meet.google.com/vej-drop-vdx", label: "De Agostini Maria", desc: "De Agostini Maria",},
{value: "https://meet.google.com/rpu-qiwt-jfs", label: "De Fino Oscar", desc: "De Fino Oscar",},
{value: "https://meet.google.com/dvw-thsa-gvo", label: "De La Torre Silvia", desc: "De La Torre Silvia",},
{value: "https://meet.google.com/pbj-xszi-zkh", label: "Defilpo Hector", desc: "Defilpo Hector",},
{value: "https://meet.google.com/zed-xnmw-sfc", label: "Diaz Maria Cristina", desc: "Diaz Maria Cristina",},
{value: "https://meet.google.com/nei-davh-ytr", label: "Dib Ricardo", desc: "Dib Ricardo",},
{value: "https://meet.google.com/nfc-qpjd-rdg", label: "Dilascio Laurent Dante Federico", desc: "Dilascio Laurent Dante Federico",},
{value: "https://meet.google.com/xgw-pjex-rdm?authuser=0", label: "Domingo Eduardo", desc: "Domingo Eduardo",},
{value: "https://meet.google.com/yua-gmfj-kqj", label: "Dominguez Hernán", desc: "Dominguez Hernán",},
{value: "https://meet.google.com/fmq-vtgv-yti", label: "Donis Nestor", desc: "Donis Nestor",},
{value: "https://meet.google.com/bjm-aefu-jut", label: "Donnadio Claudio", desc: "Donnadio Claudio",},
{value: "https://meet.google.com/yus-xpme-nrr", label: "Dracopulos Alejandro", desc: "Dracopulos Alejandro",},
{value: "https://meet.google.com/ofw-bsto-tmj", label: "Ducasse Norberto", desc: "Ducasse Norberto",},
{value: "https://meet.google.com/pxt-msuo-grk", label: "Ebrard Marcela", desc: "Ebrard Marcela",},
{value: "https://meet.google.com/xzi-grxd-beb", label: "Echegaray Pablo Martin", desc: "Echegaray Pablo Martin",},
{value: "https://meet.google.com/mbk-iunq-ouz", label: "Esteban Mariano", desc: "Esteban Mariano",},
{value: "https://meet.google.com/egc-bqjm-bnh", label: "Eterovich Emiliano", desc: "Eterovich Emiliano",},
{value: "https://meet.google.com/qvw-qogj-hdj", label: "Fanjul Osvaldo", desc: "Fanjul Osvaldo",},
{value: "https://meet.google.com/hzg-tnix-qeq", label: "Fara Hector Manuel", desc: "Fara Hector Manuel",},
{value: "https://meet.google.com/ecg-nkqu-ejc", label: "Faustino, Carlos Diego German", desc: "Faustino, Carlos Diego German",},
{value: "https://meet.google.com/ffq-bvsw-cxe", label: "Fernandez Adrián", desc: "Fernandez Adrián",},
{value: "https://meet.google.com/skx-hkue-wxr", label: "Fernandez Balbis Hernan", desc: "Fernandez Balbis Hernan",},
{value: "https://meet.google.com/gwx-hrck-zmy", label: "Fernandez Jorge", desc: "Fernandez Jorge",},
{value: "https://meet.google.com/ooa-frmr-rbm", label: "Fernandez, Guillermo Fabio", desc: "Fernandez, Guillermo Fabio",},
{value: "https://meet.google.com/sgv-tccf-rsc", label: "Fervenza, Vanesa", desc: "Fervenza, Vanesa",},
{value: "https://meet.google.com/cyz-bror-bpg", label: "Fidanza Mara", desc: "Fidanza Mara",},
{value: "https://meet.google.com/gwt-yvvn-ztj", label: "Filippi Pablo", desc: "Filippi Pablo",},
{value: "https://meet.google.com/qqk-dfdz-fzk", label: "Finale Valeria", desc: "Finale Valeria",},
{value: "https://meet.google.com/yef-ipgy-dqq", label: "Folgueras Matias", desc: "Folgueras Matias",},
{value: "https://meet.google.com/xhq-kkbz-hfw", label: "Fossemale Maria", desc: "Fossemale Maria",},
{value: "https://meet.google.com/uof-fiub-fbi", label: "Frery Juan Carlos", desc: "Frery Juan Carlos",},
{value: "https://meet.google.com/bij-bzvn-kpa", label: "Futten Armando", desc: "Futten Armando",},
{value: "https://meet.google.com/obr-myza-hgc", label: "Gamonal Lilian Graciela", desc: "Gamonal Lilian Graciela",},
{value: "https://meet.google.com/vrs-stey-ina", label: "Garay Jose", desc: "Garay Jose",},
{value: "https://meet.google.com/bhb-dxac-kef", label: "Garcia Daniel", desc: "Garcia Daniel",},
{value: "https://meet.google.com/xuk-ctib-jdo", label: "García Diego Gonzalo", desc: "García Diego Gonzalo",},
{value: "https://meet.google.com/hqh-qadj-ivi", label: "Garcia Leonardo", desc: "Garcia Leonardo",},
{value: "https://meet.google.com/rtw-oqnk-qkr", label: "Garcia Lorena", desc: "Garcia Lorena",},
{value: "https://meet.google.com/ygw-hgoi-kum", label: "Garcia Marcelo", desc: "Garcia Marcelo",},
{value: "https://meet.google.com/qtq-fyfg-sqk", label: "Garcia Marcelo Osvaldo", desc: "Garcia Marcelo Osvaldo",},
{value: "https://meet.google.com/dub-dgmy-kqr", label: "Garcia, Luciano Emmanuel", desc: "Garcia, Luciano Emmanuel",},
{value: "https://meet.google.com/mdf-iavw-ott", label: "Gentile Diego", desc: "Gentile Diego",},
{value: "https://meet.google.com/tpp-samd-ngm", label: "Gilabert Juan", desc: "Gilabert Juan",},
{value: "https://meet.google.com/pfi-bxqw-npz", label: "Gomes Rebelo, Lorena Fernanda", desc: "Gomes Rebelo, Lorena Fernanda",},
{value: "https://meet.google.com/vnz-fvwi-bba", label: "Gomez Oscar", desc: "Gomez Oscar",},
{value: "https://meet.google.com/tbs-epge-pkk", label: "Gomez Ricardo", desc: "Gomez Ricardo",},
{value: "https://meet.google.com/dje-mdax-trk", label: "Gomez Sebastian Emanuel", desc: "Gomez Sebastian Emanuel",},
{value: "https://meet.google.com/qmj-aftw-wno", label: "Gonzalez Jorge", desc: "Gonzalez Jorge",},
{value: "https://meet.google.com/yze-ebvg-sdx", label: "Gonzalez Sandra Elizabeth", desc: "Gonzalez Sandra Elizabeth",},
{value: "https://meet.google.com/yrm-qxij-wan", label: "Granito Humberto Sebastián", desc: "Granito Humberto Sebastián",},
{value: "https://meet.google.com/pvb-hjga-oen", label: "Greppi Gustavo Cesar", desc: "Greppi Gustavo Cesar",},
{value: "https://meet.google.com/uok-garz-pkn", label: "Grosso Matias Nicolas", desc: "Grosso Matias Nicolas",},
{value: "https://meet.google.com/sno-tpao-kyh", label: "Gubinelli Hernan", desc: "Gubinelli Hernan",},
{value: "https://meet.google.com/pye-vrgr-jzt", label: "Guerin Hernan", desc: "Guerin Hernan",},
{value: "https://meet.google.com/jxp-rsqp-vpf", label: "Guerrero Nicanor", desc: "Guerrero Nicanor",},
{value: "https://meet.google.com/gzt-qmsj-wwm", label: "Guglielmi Karina", desc: "Guglielmi Karina",},
{value: "https://meet.google.com/rdi-jwqw-eoe", label: "Gustavo Navone", desc: "Gustavo Navone",},
{value: "https://meet.google.com/nry-iqar-dcp", label: "Herrera Gustavo", desc: "Herrera Gustavo",},
{value: "https://meet.google.com/vgq-yjuu-xbq", label: "Horcada Marcelo", desc: "Horcada Marcelo",},
{value: "https://meet.google.com/rsy-deki-eey", label: "Horn Pedro", desc: "Horn Pedro",},
{value: "https://meet.google.com/gxk-boeq-cnt", label: "Humerez Juan", desc: "Humerez Juan",},
{value: "https://meet.google.com/tfi-pmwd-sxt", label: "Iacaruso, Andrea Susana", desc: "Iacaruso, Andrea Susana",},
{value: "https://meet.google.com/gvv-mxsj-ryx", label: "Iglesias Miguel", desc: "Iglesias Miguel",},
{value: "https://meet.google.com/mpe-snhu-kic", label: "Jar Hugo", desc: "Jar Hugo",},
{value: "https://meet.google.com/rsj-bvaa-emv", label: "Jaume  José", desc: "Jaume  José",},
{value: "https://meet.google.com/krr-kyrn-voc", label: "Jaureguilorda Maria Cristina", desc: "Jaureguilorda Maria Cristina",},
{value: "https://meet.google.com/qwd-qmsp-nff", label: "Jondet, Francisco Eduardo", desc: "Jondet, Francisco Eduardo",},
{value: "https://meet.google.com/mcj-ooke-iqi", label: "Kongrecky Marcela Claudia", desc: "Kongrecky Marcela Claudia",},
{value: "https://meet.google.com/tcm-zpba-app", label: "Kutter, Gabriela Alejandra", desc: "Kutter, Gabriela Alejandra",},
{value: "https://meet.google.com/yhp-hsat-gwj", label: "Liendo Marcos", desc: "Liendo Marcos",},
{value: "https://meet.google.com/dvk-vwxj-ukf", label: "Loggia Francisco", desc: "Loggia Francisco",},
{value: "https://meet.google.com/hjr-jnps-rqc", label: "Lopez Jorgelina", desc: "Lopez Jorgelina",},
{value: "https://meet.google.com/sqh-zxti-rrk", label: "Losasso Carolina", desc: "Losasso Carolina",},
{value: "https://meet.google.com/waw-mkkt-ovu", label: "Lozano Cristian", desc: "Lozano Cristian",},
{value: "https://meet.google.com/nzr-buuh-dnf", label: "Lunardelli Myriam", desc: "Lunardelli Myriam",},
{value: "https://meet.google.com/gfv-tdmx-ush", label: "Maffeo Eida", desc: "Maffeo Eida",},
{value: "https://meet.google.com/ufw-jcfm-eyz", label: "Manassi Alexis", desc: "Manassi Alexis",},
{value: "https://meet.google.com/rvk-dgqj-krh", label: "Mannino Natalia", desc: "Mannino Natalia",},
{value: "https://meet.google.com/srn-aopy-hqx", label: "Marazzi Flavio", desc: "Marazzi Flavio",},
{value: "https://meet.google.com/ddh-dkwg-smf", label: "Marchi Analia Veronica", desc: "Marchi Analia Veronica",},
{value: "https://meet.google.com/bdt-jfjy-ptk", label: "Marcos Guillermo", desc: "Marcos Guillermo",},
{value: "https://meet.google.com/osm-uhox-nxf", label: "Marello Romina", desc: "Marello Romina",},
{value: "https://meet.google.com/knn-jbyo-ify", label: "Marin Alberto", desc: "Marin Alberto",},
{value: "https://meet.google.com/agv-iyfy-pcj", label: "Martello Guillermo", desc: "Martello Guillermo",},
{value: "https://meet.google.com/kmo-awek-itf", label: "Martin Marcelo", desc: "Martin Marcelo",},
{value: "https://meet.google.com/gty-ubjz-bxf", label: "Martinez Claudio", desc: "Martinez Claudio",},
{value: "https://meet.google.com/yiz-hzjz-ryf", label: "Martinez Diego", desc: "Martinez Diego",},
{value: "https://meet.google.com/oek-ktev-wcd", label: "Martinez Luis", desc: "Martinez Luis",},
{value: "https://meet.google.com/yiz-pamc-zmw", label: "Martinez Silvina", desc: "Martinez Silvina",},
{value: "https://meet.google.com/amg-iyfs-srz", label: "Matorras Gabriel", desc: "Matorras Gabriel",},
{value: "https://meet.google.com/cib-askc-fiy", label: "Mauro Fabian", desc: "Mauro Fabian",},
{value: "https://meet.google.com/xtz-ofuy-mzu", label: "Mazzieri Julio", desc: "Mazzieri Julio",},
{value: "https://meet.google.com/nvm-amqp-yhf", label: "Meilij, Liliana", desc: "Meilij, Liliana",},
{value: "https://meet.google.com/oej-oxxf-njw", label: "Merlo Gaston", desc: "Merlo Gaston",},
{value: "https://meet.google.com/pmq-ixvx-hhj", label: "Messina, Hernan Javier", desc: "Messina, Hernan Javier",},
{value: "https://meet.google.com/pvj-fjff-qeo", label: "Miele Ariel", desc: "Miele Ariel",},
{value: "https://meet.google.com/syd-uycq-pyb", label: "Miño Diego Armando", desc: "Miño Diego Armando",},
{value: "https://meet.google.com/isi-ofrk-hri", label: "Molina Daniel", desc: "Molina Daniel",},
{value: "https://meet.google.com/xnu-ngwn-cce", label: "Mollo Augusto Damian", desc: "Mollo Augusto Damian",},
{value: "https://meet.google.com/met-bzcj-jtv", label: "Montes Pita, Maria", desc: "Montes Pita, Maria",},
{value: "https://meet.google.com/eks-qrrm-wji", label: "Mora Marcela", desc: "Mora Marcela",},
{value: "https://meet.google.com/cjy-dsfo-yii", label: "Morgante Adrian", desc: "Morgante Adrian",},
{value: "https://meet.google.com/gcc-krjc-qzd", label: "Mulki Mario", desc: "Mulki Mario",},
{value: "https://meet.google.com/tcd-oika-iqx", label: "Muro Verónica Andrea", desc: "Muro Verónica Andrea",},
{value: "https://meet.google.com/mzk-zewq-hjh", label: "Nacer Francisco José", desc: "Nacer Francisco José",},
{value: "https://meet.google.com/fqm-smdr-xvb", label: "Nazar Ruben", desc: "Nazar Ruben",},
{value: "https://meet.google.com/rtr-kzke-dbr", label: "Noriega Ismael", desc: "Noriega Ismael",},
{value: "https://meet.google.com/vas-xmmw-nbg", label: "Nosetto Marcelo", desc: "Nosetto Marcelo",},
{value: "https://meet.google.com/ohd-yuhj-iyi", label: "Novoa Sebastian Ariel", desc: "Novoa Sebastian Ariel",},
{value: "https://meet.google.com/fwm-ytsg-gzn", label: "Nuñez Ariel", desc: "Nuñez Ariel",},
{value: "https://meet.google.com/fpy-gvud-hzh", label: "Ocampo Martin", desc: "Ocampo Martin",},
{value: "https://meet.google.com/vaf-nuua-nxo", label: "Odiz Alberto", desc: "Odiz Alberto",},
{value: "https://meet.google.com/vee-gkgx-ext", label: "Oliveto, Gabriel Oscar", desc: "Oliveto, Gabriel Oscar",},
{value: "https://meet.google.com/sai-safj-anx", label: "Orlando Marcelo", desc: "Orlando Marcelo",},
{value: "https://meet.google.com/nxi-yyif-jbj", label: "Ostrowski Ruben", desc: "Ostrowski Ruben",},
{value: "https://meet.google.com/ibv-dumm-qpd", label: "Pacheco Jesica", desc: "Pacheco Jesica",},
{value: "https://meet.google.com/zbd-icik-nge", label: "Paladino Huber", desc: "Paladino Huber",},
{value: "https://meet.google.com/vnk-fhtr-yrz", label: "Pardo Ruben", desc: "Pardo Ruben",},
{value: "https://meet.google.com/eci-xmrp-vbn", label: "Parodi Maria Victoria", desc: "Parodi Maria Victoria",},
{value: "https://meet.google.com/jpj-gtjx-fwu", label: "Paz Ariel", desc: "Paz Ariel",},
{value: "https://meet.google.com/xtb-ajox-sjo", label: "Petrus Alejandro", desc: "Petrus Alejandro",},
{value: "https://meet.google.com/dzs-hfqr-pbb", label: "Pianesi Matias Alejandro", desc: "Pianesi Matias Alejandro",},
{value: "https://meet.google.com/dqj-mboe-bux", label: "Posta Pablo", desc: "Posta Pablo",},
{value: "https://meet.google.com/epa-xeto-ydk", label: "Pritzker Sebastian", desc: "Pritzker Sebastian",},
{value: "https://meet.google.com/rzb-teoi-zyp", label: "Pucheta Juan Manuel", desc: "Pucheta Juan Manuel",},
{value: "https://meet.google.com/cbk-wyea-snz", label: "Puente Gustavo", desc: "Puente Gustavo",},
{value: "https://meet.google.com/byq-ijsa-ijk", label: "Quintana Natalia", desc: "Quintana Natalia",},
{value: "https://meet.google.com/ykc-mtoj-uow", label: "Quinteros Hugo", desc: "Quinteros Hugo",},
{value: "https://meet.google.com/uar-cgfu-fvs", label: "Raffetto Russo Valeria", desc: "Raffetto Russo Valeria",},
{value: "https://meet.google.com/sce-ccgp-hsy", label: "Raimondo Hernan", desc: "Raimondo Hernan",},
{value: "https://meet.google.com/ntg-qsyq-uod", label: "Raimundo Sebastian", desc: "Raimundo Sebastian",},
{value: "https://meet.google.com/psc-mwwd-xcb", label: "Ramospe Horacio", desc: "Ramospe Horacio",},
{value: "https://meet.google.com/kad-nrsm-jjw", label: "Ranua Mauro", desc: "Ranua Mauro",},
{value: "https://meet.google.com/vxh-xibo-mtx", label: "Ratt Mario", desc: "Ratt Mario",},
{value: "https://meet.google.com/ayf-edsm-nhc", label: "Reynolds Fernando", desc: "Reynolds Fernando",},
{value: "https://meet.google.com/urc-ncnp-ojv", label: "Ricca Reitober Maximiliano Joaquin", desc: "Ricca Reitober Maximiliano Joaquin",},
{value: "https://meet.google.com/xsb-cych-eds", label: "Ricetti Gustavo Enrique", desc: "Ricetti Gustavo Enrique",},
{value: "https://meet.google.com/rvc-gxmd-xhp", label: "Richards Carlos", desc: "Richards Carlos",},
{value: "https://meet.google.com/fcn-qctu-iyw", label: "Rios Cesar", desc: "Rios Cesar",},
{value: "https://meet.google.com/fva-wgka-hvv", label: "Robles Héctor", desc: "Robles Héctor",},
{value: "https://meet.google.com/gcv-vfqt-qab", label: "Rodriguez Ernesto", desc: "Rodriguez Ernesto",},
{value: "https://meet.google.com/vpd-qdgp-jkn", label: "Rodriguez Goy Ruben", desc: "Rodriguez Goy Ruben",},
{value: "https://meet.google.com/gsw-unmt-okw", label: "Rodriguez Javier", desc: "Rodriguez Javier",},
{value: "https://meet.google.com/uxs-tafs-iya", label: "Rodriguez Walter", desc: "Rodriguez Walter",},
{value: "https://meet.google.com/kui-awhx-fev", label: "Rofeld Daniel", desc: "Rofeld Daniel",},
{value: "https://meet.google.com/fjr-pqer-gch", label: "Rolando Gabriel", desc: "Rolando Gabriel",},
{value: "https://meet.google.com/brj-fmmf-pph", label: "Rolla José Matias", desc: "Rolla José Matias",},
{value: "https://meet.google.com/ugt-vqpf-epp", label: "Romanazzi Ricardo", desc: "Romanazzi Ricardo",},
{value: "https://meet.google.com/rtb-xtos-qry", label: "Romero Beatriz", desc: "Romero Beatriz",},
{value: "https://meet.google.com/umy-incf-dcm", label: "Rosasco Flavio Alejandro", desc: "Rosasco Flavio Alejandro",},
{value: "https://meet.google.com/skg-azhh-uyq", label: "Rosquellas Maria", desc: "Rosquellas Maria",},
{value: "https://meet.google.com/knm-sgds-bmj", label: "Rossini Sandra", desc: "Rossini Sandra",},
{value: "https://meet.google.com/jue-hoep-uin", label: "Rovira Luis", desc: "Rovira Luis",},
{value: "https://meet.google.com/ifj-qapn-hat", label: "Rubin Gustavo", desc: "Rubin Gustavo",},
{value: "https://meet.google.com/zgs-tthd-iaw", label: "Sagnes Bernardo Andres", desc: "Sagnes Bernardo Andres",},
{value: "https://meet.google.com/okh-okug-bpj", label: "Salinas Federico Mariano", desc: "Salinas Federico Mariano",},
{value: "https://meet.google.com/iep-ewut-qww", label: "Sanchez Héctor Fabio", desc: "Sanchez Héctor Fabio",},
{value: "https://meet.google.com/iyt-faoq-vdx", label: "Saporito Soledad", desc: "Saporito Soledad",},
{value: "https://meet.google.com/snb-qbdu-vwp", label: "Saucedo Aguirre Jose", desc: "Saucedo Aguirre Jose",},
{value: "https://meet.google.com/iyy-ncqn-msj", label: "Savastano Emilio", desc: "Savastano Emilio",},
{value: "https://meet.google.com/qmv-hkap-pqt", label: "Savoia Vanina", desc: "Savoia Vanina",},
{value: "https://meet.google.com/krm-kota-hyo", label: "Schmidt, Gabriela Cristina", desc: "Schmidt, Gabriela Cristina",},
{value: "https://meet.google.com/azs-qifa-djo", label: "Schneider Matias David", desc: "Schneider Matias David",},
{value: "https://meet.google.com/cna-efov-jmv", label: "Scoppeta Lucrecia", desc: "Scoppeta Lucrecia",},
{value: "https://meet.google.com/cjy-dsfo-yii", label: "Senatore Adriana", desc: "Senatore Adriana",},
{value: "https://meet.google.com/gnd-frjo-dsg", label: "Serquella Jorge", desc: "Serquella Jorge",},
{value: "https://meet.google.com/gcd-vvfm-dut", label: "Soto Alejandro", desc: "Soto Alejandro",},
{value: "https://meet.google.com/yeu-mpnd-cwi", label: "Soto Veronica", desc: "Soto Veronica",},
{value: "https://meet.google.com/jgr-rqmd-qxd", label: "Souto Roberto", desc: "Souto Roberto",},
{value: "https://meet.google.com/xxu-xgxk-xjh", label: "Spinetta Jorge", desc: "Spinetta Jorge",},
{value: "https://meet.google.com/oqq-atqg-saq", label: "Spinoso Fabian", desc: "Spinoso Fabian",},
{value: "https://meet.google.com/hmi-xvgd-ctf", label: "Strficek Irene", desc: "Strficek Irene",},
{value: "https://meet.google.com/haa-dafi-pcs", label: "Suarez Sergio Hugo", desc: "Suarez Sergio Hugo",},
{value: "https://meet.google.com/auq-veri-sdn", label: "Subeldia Enzo", desc: "Subeldia Enzo",},
{value: "https://meet.google.com/keo-ymri-pkc", label: "Tarantino Jorge", desc: "Tarantino Jorge",},
{value: "https://meet.google.com/xnp-rrwz-mwx", label: "Tau Gabriel", desc: "Tau Gabriel",},
{value: "https://meet.google.com/nma-qfqa-skt", label: "Traglio Mariano", desc: "Traglio Mariano",},
{value: "https://meet.google.com/qcj-ahdq-nyv", label: "Traverso Enrique", desc: "Traverso Enrique",},
{value: "https://meet.google.com/frw-hjrd-bfp", label: "Traverso Julio", desc: "Traverso Julio",},
{value: "https://meet.google.com/siv-ytap-pum", label: "Trevisonno Andres Anibal", desc: "Trevisonno Andres Anibal",},
{value: "https://meet.google.com/psj-abqf-eyp", label: "Trost Alberto", desc: "Trost Alberto",},
{value: "https://meet.google.com/aha-nowv-twf", label: "Trujillo Tamara", desc: "Trujillo Tamara",},
{value: "https://meet.google.com/tgo-faer-qtt", label: "Ulloa Hugo", desc: "Ulloa Hugo",},
{value: "https://meet.google.com/yif-efuj-tyo", label: "Urretavizcaya Jose", desc: "Urretavizcaya Jose",},
{value: "https://meet.google.com/vtw-yzqo-due", label: "Valerio Guillermo", desc: "Valerio Guillermo",},
{value: "https://meet.google.com/qbk-reiz-vod", label: "Vallejo Pablo", desc: "Vallejo Pablo",},
{value: "https://meet.google.com/zmq-hwus-cbq", label: "Varela Juan", desc: "Varela Juan",},
{value: "https://meet.google.com/zfk-pghs-kax", label: "Vasto Andres", desc: "Vasto Andres",},
{value: "https://meet.google.com/nsp-ffdf-imz", label: "Vega Horacio", desc: "Vega Horacio",},
{value: "https://meet.google.com/jed-qnpn-qww", label: "Velardez Gabriela", desc: "Velardez Gabriela",},
{value: "https://meet.google.com/ohs-dqhp-vrx", label: "Ventura Jorge", desc: "Ventura Jorge",},
{value: "https://meet.google.com/hrc-xcdo-sdx", label: "Venturi Maria Julieta", desc: "Venturi Maria Julieta",},
{value: "https://meet.google.com/wwu-kwon-eud", label: "Vicente Rodrigo", desc: "Vicente Rodrigo",},
{value: "https://meet.google.com/tan-qhki-akd", label: "Vidal Jorge Elias", desc: "Vidal Jorge Elias",},
{value: "https://meet.google.com/hff-hvuc-tgi", label: "Viggiano Oscar Emmanuel", desc: "Viggiano Oscar Emmanuel",},
{value: "https://meet.google.com/dnk-vqct-tdr", label: "Villanueva Pablo", desc: "Villanueva Pablo",},
{value: "https://meet.google.com/ijz-fihp-zfj", label: "Vivas Walter", desc: "Vivas Walter",},
{value: "https://meet.google.com/jxz-gzyu-gdv", label: "Ybarra Daniel", desc: "Ybarra Daniel",},
{value: "https://meet.google.com/rkt-cqhf-eoo", label: "Yennerich Damian", desc: "Yennerich Damian",},
{value: "https://meet.google.com/bhf-cmec-xcf", label: "Zabala Laura Ileana", desc: "Zabala Laura Ileana",},
{value: "https://meet.google.com/sxf-pjzu-jfs", label: "Zilleruelo Gustavo", desc: "Zilleruelo Gustavo",},
    ];
 
    $( "#project" ).autocomplete({
      minLength: 0,
      source: projects,
      focus: function( event, ui ) {
        $( "#project" ).val( ui.item.desc );
        return false;
      },
      select: function( event, ui ) {
        $( "#project" ).val( ui.item.desc);
        $( "#project-id" ).val( ui.item.value );
        $( "#project-description" ).html( ui.item.value);
        $( "#project-icon" ).attr( "src", "images/" + ui.item.icon );
        ir_a();
        return false;
      }
    })
    .autocomplete( "instance" )._renderItem = function( ul, item ) {
      return $( "<li>" )
//        .append( "<div>" + item.label + "<br>" + item.desc + "</div>" )
        .append( "<div>" + item.desc + "</div>" )
        .appendTo( ul );
    };
  } );

//submit
    function ir_a(){
    var link = null;
    link = document.getElementById("project-id").value;
    window.location.href = "https://" + link;
        };
