  $( function() {
    var projects = [
{value: "http://bit.ly/claudiaaboal", label: "Aboal Claudia", desc: "Aboal Claudia",},
{value: "http://bit.ly/acerrapatricia", label: "Acerra Patricia", desc: "Acerra Patricia",},
{value: "http://bit.ly/acostaguillermo", label: "Acosta Guillermo", desc: "Acosta Guillermo",},
{value: "http://bit.ly/adragnaclaudio", label: "Adragna Claudio", desc: "Adragna Claudio",},
{value: "http://bit.ly/agueiradiego", label: "Agueira Diego", desc: "Agueira Diego",},
{value: "http://bit.ly/albinruben", label: "Albin Ruben", desc: "Albin Ruben",},
{value: "http://bit.ly/alcarazcesar", label: "Alcaraz Cesar", desc: "Alcaraz Cesar",},
{value: "http://bit.ly/almarazadrian", label: "Almaraz Adrian", desc: "Almaraz Adrian",},
{value: "http://bit.ly/altamiralaura", label: "Altamira Laura", desc: "Altamira Laura",},
{value: "http://bit.ly/alumaveronica", label: "Aluma Verónica", desc: "Aluma Verónica",},
{value: "http://bit.ly/ammiraticlaudio", label: "Ammirati Claudio", desc: "Ammirati Claudio",},
{value: "http://bit.ly/fabricioandre", label: "Andre Fabricio", desc: "Andre Fabricio",},
{value: "http://bit.ly/araujoraul", label: "Araujo Raúl", desc: "Araujo Raúl",},
{value: "http://bit.ly/pabloarce", label: "Arce Cristian Pablo", desc: "Arce Cristian Pablo",},
{value: "http://bit.ly/aridalucia", label: "Arida Lucila", desc: "Arida Lucila",},
{value: "http://bit.ly/arraezmaria", label: "Arraez Maria Sol", desc: "Arraez Maria Sol",},
{value: "http://bit.ly/arschinovcesar", label: "Arschinov César", desc: "Arschinov César",},
{value: "http://bit.ly/avaloseduardo", label: "Avalos Eduardo", desc: "Avalos Eduardo",},
{value: "http://bit.ly/badoorlando", label: "Bado Orlando", desc: "Bado Orlando",},
{value: "http://bit.ly/bahamodeznicolas", label: "Bahamodez Nicolas", desc: "Bahamodez Nicolas",},
{value: "http://bit.ly/marcelobarbieri", label: "Barbieri Marcelo", desc: "Barbieri Marcelo",},
{value: "http://bit.ly/bausiliovicente", label: "Bausilio Vicente", desc: "Bausilio Vicente",},
{value: "http://bit.ly/baylacmaria", label: "Baylac Maria", desc: "Baylac Maria",},
{value: "http://bit.ly/borodowskifernando", label: "Borodowski Fernando", desc: "Borodowski Fernando",},
{value: "http://bit.ly/bozziniandrea", label: "Bozzini Andrea", desc: "Bozzini Andrea",},
{value: "http://bit.ly/bringascristina", label: "Bringas Cristina", desc: "Bringas Cristina",},
{value: "http://bit.ly/brunocecilia", label: "Bruno Cecilia", desc: "Bruno Cecilia",},
{value: "http://bit.ly/buchmullercarlos", label: "Buchmuller Carlos", desc: "Buchmuller Carlos",},
{value: "http://bit.ly/buffoniantonella", label: "Buffoni, Antonella Maria", desc: "Buffoni, Antonella Maria",},
{value: "http://bit.ly/busatopaola", label: "Busato Paola", desc: "Busato Paola",},
{value: "http://bit.ly/gastonbustos", label: "Bustos Gaston Miguel", desc: "Bustos Gaston Miguel",},
{value: "http://bit.ly/camarapatricia", label: "Camara Patricia", desc: "Camara Patricia",},
{value: "http://bit.ly/mauriciocamargo", label: "Camargo Mauricio", desc: "Camargo Mauricio",},
{value: "http://bit.ly/camposjose", label: "Campos José Evaristo", desc: "Campos José Evaristo",},
{value: "http://bit.ly/canterajuanpablo", label: "Cantera Juan Pablo", desc: "Cantera Juan Pablo",},
{value: "http://bit.ly/canterosvictor", label: "Canteros Víctor", desc: "Canteros Víctor",},
{value: "http://bit.ly/capolungoroberto", label: "Capolungo Roberto", desc: "Capolungo Roberto",},
{value: "http://bit.ly/pablocapriotti", label: "Capriotti Pablo", desc: "Capriotti Pablo",},
{value: "http://bit.ly/carabellilia", label: "Carabelli Lia Gabriela", desc: "Carabelli Lia Gabriela",},
{value: "http://bit.ly/carassaimatias", label: "Carassai Matias Alfredo", desc: "Carassai Matias Alfredo",},
{value: "http://bit.ly/cardonettijuancarlos", label: "Cardonetti Juan Carlos", desc: "Cardonetti Juan Carlos",},
{value: "http://bit.ly/carussogabriel", label: "Carusso Dante Gabriel", desc: "Carusso Dante Gabriel",},
{value: "http://bit.ly/castrocaucarlos", label: "Castro Cau Julia Carlos Silvestre", desc: "Castro Cau Julia Carlos Silvestre",},
{value: "http://bit.ly/castromariana", label: "Castro, Mariana Mercedes", desc: "Castro, Mariana Mercedes",},
{value: "http://bit.ly/cavigliamariano", label: "Caviglia Mariano", desc: "Caviglia Mariano",},
{value: "http://bit.ly/cedroviviana", label: "Cedro Viviana", desc: "Cedro Viviana",},
{value: "http://bit.ly/cerviñomarcelo", label: "Cerviño Marcelo", desc: "Cerviño Marcelo",},
{value: "https://bit.ly/3gdksui", label: "Chamorro Jorge", desc: "Chamorro Jorge",},
{value: "http://bit.ly/ciappinoalejandro", label: "Ciappino Alejandro", desc: "Ciappino Alejandro",},
{value: "http://bit.ly/clofederico", label: "Clos Federico", desc: "Clos Federico",},
{value: "http://bit.ly/colombogustavo", label: "Colombo Gustavo", desc: "Colombo Gustavo",},
{value: "http://bit.ly/cordobajuanmanuel", label: "Cordoba Juan Manuel", desc: "Cordoba Juan Manuel",},
{value: "http://bit.ly/coriglianoantonio", label: "Corigliano Antonio", desc: "Corigliano Antonio",},
{value: "http://bit.ly/corniglione", label: "Corniglione Rivero  J.", desc: "Corniglione Rivero  J.",},
{value: "http://bit.ly/coronatojeronimo", label: "Coronato Jerónimo", desc: "Coronato Jerónimo",},
{value: "http://bit.ly/correaguillermo", label: "Correa Guillermo", desc: "Correa Guillermo",},
{value: "http://bit.ly/cortesesilvina", label: "Cortese Silvina", desc: "Cortese Silvina",},
{value: "http://bit.ly/cousoalejandro", label: "Couso Alejandro", desc: "Couso Alejandro",},
{value: "http://bit.ly/cousosergio", label: "Couso Sergio", desc: "Couso Sergio",},
{value: "http://bit.ly/crottialejandra", label: "Crotti Alejandra", desc: "Crotti Alejandra",},
{value: "http://bit.ly/cruzateruben", label: "Cruzate Edgardo", desc: "Cruzate Edgardo",},
{value: "http://bit.ly/daprajavier", label: "Da Prá Javier Eduardo", desc: "Da Prá Javier Eduardo",},
{value: "http://bit.ly/dahersergio", label: "Daher Sergio", desc: "Daher Sergio",},
{value: "http://bit.ly/deagostinimaria", label: "De Agostini Maria", desc: "De Agostini Maria",},
{value: "http://bit.ly/definooscar", label: "De Fino Oscar", desc: "De Fino Oscar",},
{value: "http://bit.ly/delatorresilvia", label: "De La Torre Silvia", desc: "De La Torre Silvia",},
{value: "http://bit.ly/delfipohector", label: "Defilpo Hector", desc: "Defilpo Hector",},
{value: "http://bit.ly/diazmariacristina", label: "Diaz Maria Cristina", desc: "Diaz Maria Cristina",},
{value: "http://bit.ly/dibricardo", label: "Dib Ricardo", desc: "Dib Ricardo",},
{value: "http://bit.ly/dilasciodante", label: "Dilascio Laurent Dante Federico", desc: "Dilascio Laurent Dante Federico",},
{value: "http://bit.ly/eduardodomingo", label: "Domingo Eduardo", desc: "Domingo Eduardo",},
{value: "http://bit.ly/hernandominguez", label: "Dominguez Hernán", desc: "Dominguez Hernán",},
{value: "http://bit.ly/donisnestor", label: "Donis Nestor", desc: "Donis Nestor",},
{value: "http://bit.ly/donnadioclaudio", label: "Donnadio Claudio", desc: "Donnadio Claudio",},
{value: "http://bit.ly/dracopulosalejandro", label: "Dracopulos Alejandro", desc: "Dracopulos Alejandro",},
{value: "http://bit.ly/ducassenorberto", label: "Ducasse Norberto", desc: "Ducasse Norberto",},
{value: "http://bit.ly/ebrardmarcela", label: "Ebrard Marcela", desc: "Ebrard Marcela",},
{value: "http://bit.ly/etchegaraypablo", label: "Echegaray Pablo Martin", desc: "Echegaray Pablo Martin",},
{value: "http://bit.ly/estebanmariano", label: "Esteban Mariano", desc: "Esteban Mariano",},
{value: "http://bit.ly/eterovichemiliano", label: "Eterovich Emiliano", desc: "Eterovich Emiliano",},
{value: "http://bit.ly/fanjulosvaldo", label: "Fanjul Osvaldo", desc: "Fanjul Osvaldo",},
{value: "http://bit.ly/farahector", label: "Fara Hector Manuel", desc: "Fara Hector Manuel",},
{value: "http://bit.ly/faustinocarlos", label: "Faustino, Carlos Diego German", desc: "Faustino, Carlos Diego German",},
{value: "http://bit.ly/fernandezadrian", label: "Fernandez Adrián", desc: "Fernandez Adrián",},
{value: "http://bit.ly/fernandezbalbishernan", label: "Fernandez Balbis Hernan", desc: "Fernandez Balbis Hernan",},
{value: "http://bit.ly/fernandezjorge", label: "Fernandez Jorge", desc: "Fernandez Jorge",},
{value: "http://bit.ly/fernandezguillermo", label: "Fernandez, Guillermo Fabio", desc: "Fernandez, Guillermo Fabio",},
{value: "http://bit.ly/fervenzavanesa", label: "Fervenza, Vanesa", desc: "Fervenza, Vanesa",},
{value: "http://bit.ly/fidanzamara", label: "Fidanza Mara", desc: "Fidanza Mara",},
{value: "http://bit.ly/filippipablo", label: "Filippi Pablo", desc: "Filippi Pablo",},
{value: "http://bit.ly/finalevaleria", label: "Finale Valeria", desc: "Finale Valeria",},
{value: "http://bit.ly/folguerasmatias", label: "Folgueras Matias", desc: "Folgueras Matias",},
{value: "http://bit.ly/fossemalematias", label: "Fossemale Maria", desc: "Fossemale Maria",},
{value: "http://bit.ly/frerycarlos", label: "Frery Juan Carlos", desc: "Frery Juan Carlos",},
{value: "http://bit.ly/fluttenarmando", label: "Futten Armando", desc: "Futten Armando",},
{value: "http://bit.ly/gamonallilian", label: "Gamonal Lilian Graciela", desc: "Gamonal Lilian Graciela",},
{value: "http://bit.ly/garayjose", label: "Garay Jose", desc: "Garay Jose",},
{value: "http://bit.ly/garciadaniel", label: "Garcia Daniel", desc: "Garcia Daniel",},
{value: "http://bit.ly/garciadiegogonzalo", label: "García Diego Gonzalo", desc: "García Diego Gonzalo",},
{value: "http://bit.ly/garcialeonardo", label: "Garcia Leonardo", desc: "Garcia Leonardo",},
{value: "http://bit.ly/garcialorena", label: "Garcia Lorena", desc: "Garcia Lorena",},
{value: "http://bit.ly/garciamarcelo", label: "Garcia Marcelo", desc: "Garcia Marcelo",},
{value: "http://bit.ly/garciaosvaldo", label: "Garcia Marcelo Osvaldo", desc: "Garcia Marcelo Osvaldo",},
{value: "http://bit.ly/garcialuciano", label: "Garcia, Luciano Emmanuel", desc: "Garcia, Luciano Emmanuel",},
{value: "http://bit.ly/gentilediego", label: "Gentile Diego", desc: "Gentile Diego",},
{value: "http://bit.ly/gilabertjuan", label: "Gilabert Juan", desc: "Gilabert Juan",},
{value: "http://bit.ly/gomezrebelolorena", label: "Gomes Rebelo, Lorena Fernanda", desc: "Gomes Rebelo, Lorena Fernanda",},
{value: "-", label: "Gomez Oscar", desc: "Gomez Oscar",},
{value: "http://bit.ly/gomezricardo", label: "Gomez Ricardo", desc: "Gomez Ricardo",},
{value: "http://bit.ly/gomezsebastian", label: "Gomez Sebastian Emanuel", desc: "Gomez Sebastian Emanuel",},
{value: "http://bit.ly/gonzalezjorge", label: "Gonzalez Jorge", desc: "Gonzalez Jorge",},
{value: "http://bit.ly/gonzalezsandra", label: "Gonzalez Sandra Elizabeth", desc: "Gonzalez Sandra Elizabeth",},
{value: "http://bit.ly/granitohumberto", label: "Granito Humberto Sebastián", desc: "Granito Humberto Sebastián",},
{value: "http://bit.ly/greppigustavo", label: "Greppi Gustavo Cesar", desc: "Greppi Gustavo Cesar",},
{value: "http://bit.ly/matiasgrosso", label: "Grosso Matias Nicolas", desc: "Grosso Matias Nicolas",},
{value: "http://bit.ly/hernangubinelli", label: "Gubinelli Hernan", desc: "Gubinelli Hernan",},
{value: "http://bit.ly/guerinhernan", label: "Guerin Hernan", desc: "Guerin Hernan",},
{value: "http://bit.ly/guerreronicanor", label: "Guerrero Nicanor", desc: "Guerrero Nicanor",},
{value: "http://bit.ly/guglielmicarina", label: "Guglielmi Karina", desc: "Guglielmi Karina",},
{value: "http://bit.ly/navonegustavo", label: "Gustavo Navone", desc: "Gustavo Navone",},
{value: "http://bit.ly/herreragustavo", label: "Herrera Gustavo", desc: "Herrera Gustavo",},
{value: "http://bit.ly/horcadamarcelo", label: "Horcada Marcelo", desc: "Horcada Marcelo",},
{value: "http://bit.ly/hornpedro", label: "Horn Pedro", desc: "Horn Pedro",},
{value: "http://bit.ly/humerezjuan", label: "Humerez Juan", desc: "Humerez Juan",},
{value: "http://bit.ly/iacarusoandrea", label: "Iacaruso, Andrea Susana", desc: "Iacaruso, Andrea Susana",},
{value: "http://bit.ly/iglesiasmiguel", label: "Iglesias Miguel", desc: "Iglesias Miguel",},
{value: "http://bit.ly/jarhugo", label: "Jar Hugo", desc: "Jar Hugo",},
{value: "http://bit.ly/jaumejose", label: "Jaume  José", desc: "Jaume  José",},
{value: "http://bit.ly/jaureguilordacristina", label: "Jaureguilorda Maria Cristina", desc: "Jaureguilorda Maria Cristina",},
{value: "http://bit.ly/jondetfrancisco", label: "Jondet, Francisco Eduardo", desc: "Jondet, Francisco Eduardo",},
{value: "http://bit.ly/kongreckymarcela", label: "Kongrecky Marcela Claudia", desc: "Kongrecky Marcela Claudia",},
{value: "http://bit.ly/kuttergabriela", label: "Kutter, Gabriela Alejandra", desc: "Kutter, Gabriela Alejandra",},
{value: "http://bit.ly/marcosliendo", label: "Liendo Marcos", desc: "Liendo Marcos",},
{value: "http://bit.ly/loggiafrancisco", label: "Loggia Francisco", desc: "Loggia Francisco",},
{value: "http://bit.ly/lopezjorgelina", label: "Lopez Jorgelina", desc: "Lopez Jorgelina",},
{value: "http://bit.ly/losassocarolina", label: "Losasso Carolina", desc: "Losasso Carolina",},
{value: "http://bit.ly/lozanocristian", label: "Lozano Cristian", desc: "Lozano Cristian",},
{value: "http://bit.ly/lunardellimyriam", label: "Lunardelli Myriam", desc: "Lunardelli Myriam",},
{value: "http://bit.ly/maffeoeida", label: "Maffeo Eida", desc: "Maffeo Eida",},
{value: "http://bit.ly/manassialexis", label: "Manassi Alexis", desc: "Manassi Alexis",},
{value: "http://bit.ly/manninonatalia", label: "Mannino Natalia", desc: "Mannino Natalia",},
{value: "http://bit.ly/marazziflavio", label: "Marazzi Flavio", desc: "Marazzi Flavio",},
{value: "http://bit.ly/marchianalia", label: "Marchi Analia Veronica", desc: "Marchi Analia Veronica",},
{value: "http://bit.ly/marcosguillermo", label: "Marcos Guillermo", desc: "Marcos Guillermo",},
{value: "http://bit.ly/marelloromina", label: "Marello Romina", desc: "Marello Romina",},
{value: "http://bit.ly/marinalberto", label: "Marin Alberto", desc: "Marin Alberto",},
{value: "http://bit.ly/martelloguillermo", label: "Martello Guillermo", desc: "Martello Guillermo",},
{value: "http://bit.ly/martinmarcelo", label: "Martin Marcelo", desc: "Martin Marcelo",},
{value: "http://bit.ly/martinezclaudio", label: "Martinez Claudio", desc: "Martinez Claudio",},
{value: "http://bit.ly/martinezdiego", label: "Martinez Diego", desc: "Martinez Diego",},
{value: "http://bit.ly/martinezluis", label: "Martinez Luis", desc: "Martinez Luis",},
{value: "http://bit.ly/martinezsilvina", label: "Martinez Silvina", desc: "Martinez Silvina",},
{value: "https://bit.ly/matorrasgabriel", label: "Matorras Gabriel", desc: "Matorras Gabriel",},
{value: "http://bit.ly/maurofabian", label: "Mauro Fabian", desc: "Mauro Fabian",},
{value: "http://bit.ly/juliomazzieri", label: "Mazzieri Julio", desc: "Mazzieri Julio",},
{value: "http://bit.ly/meilijliliana", label: "Meilij, Liliana", desc: "Meilij, Liliana",},
{value: "http://bit.ly/merlogaston", label: "Merlo Gaston", desc: "Merlo Gaston",},
{value: "http://bit.ly/messinahernan", label: "Messina, Hernan Javier", desc: "Messina, Hernan Javier",},
{value: "http://bit.ly/mieleariel", label: "Miele Ariel", desc: "Miele Ariel",},
{value: "http://bit.ly/miñodiego", label: "Miño Diego Armando", desc: "Miño Diego Armando",},
{value: "http://bit.ly/molinadaniel", label: "Molina Daniel", desc: "Molina Daniel",},
{value: "http://bit.ly/molloaugusto", label: "Mollo Augusto Damian", desc: "Mollo Augusto Damian",},
{value: "http://bit.ly/montespitamaria", label: "Montes Pita, Maria", desc: "Montes Pita, Maria",},
{value: "http://bit.ly/moramarcela", label: "Mora Marcela", desc: "Mora Marcela",},
{value: "http://bit.ly/morganteadrian", label: "Morgante Adrian", desc: "Morgante Adrian",},
{value: "http://bit.ly/mulkimario", label: "Mulki Mario", desc: "Mulki Mario",},
{value: "http://bit.ly/muroveronica", label: "Muro Verónica Andrea", desc: "Muro Verónica Andrea",},
{value: "http://bit.ly/nacerfrancisco", label: "Nacer Francisco José", desc: "Nacer Francisco José",},
{value: "http://bit.ly/nazarruben", label: "Nazar Ruben", desc: "Nazar Ruben",},
{value: "http://bit.ly/noriegaismael", label: "Noriega Ismael", desc: "Noriega Ismael",},
{value: "http://bit.ly/nossettomercelo", label: "Nosetto Marcelo", desc: "Nosetto Marcelo",},
{value: "http://bit.ly/novoasebastian", label: "Novoa Sebastian Ariel", desc: "Novoa Sebastian Ariel",},
{value: "http://bit.ly/arielnuñez", label: "Nuñez Ariel", desc: "Nuñez Ariel",},
{value: "http://bit.ly/martinocampo", label: "Ocampo Martin", desc: "Ocampo Martin",},
{value: "http://bit.ly/odizalberto", label: "Odiz Alberto", desc: "Odiz Alberto",},
{value: "http://bit.ly/olivettogabriel", label: "Oliveto, Gabriel Oscar", desc: "Oliveto, Gabriel Oscar",},
{value: "http://bit.ly/orlandomarcelo", label: "Orlando Marcelo", desc: "Orlando Marcelo",},
{value: "http://bit.ly/ostrowskiruben", label: "Ostrowski Ruben", desc: "Ostrowski Ruben",},
{value: "http://bit.ly/pachecojesica", label: "Pacheco Jesica", desc: "Pacheco Jesica",},
{value: "http://bit.ly/paladinohuber", label: "Paladino Huber", desc: "Paladino Huber",},
{value: "http://bit.ly/pardoruben", label: "Pardo Ruben", desc: "Pardo Ruben",},
{value: "http://bit.ly/parodimaria", label: "Parodi Maria Victoria", desc: "Parodi Maria Victoria",},
{value: "http://bit.ly/pazariel", label: "Paz Ariel", desc: "Paz Ariel",},
{value: "http://bit.ly/petrusalejandro", label: "Petrus Alejandro", desc: "Petrus Alejandro",},
{value: "http://bit.ly/pianessimatias", label: "Pianesi Matias Alejandro", desc: "Pianesi Matias Alejandro",},
{value: "http://bit.ly/postapablo", label: "Posta Pablo", desc: "Posta Pablo",},
{value: "http://bit.ly/pritzkersebastian", label: "Pritzker Sebastian", desc: "Pritzker Sebastian",},
{value: "http://bit.ly/puchetajuanmanuel", label: "Pucheta Juan Manuel", desc: "Pucheta Juan Manuel",},
{value: "http://bit.ly/puentegustavo", label: "Puente Gustavo", desc: "Puente Gustavo",},
{value: "http://bit.ly/quintananatalia", label: "Quintana Natalia", desc: "Quintana Natalia",},
{value: "http://bit.ly/quinteroshugo", label: "Quinteros Hugo", desc: "Quinteros Hugo",},
{value: "http://bit.ly/valeriaraffetto", label: "Raffetto Russo Valeria", desc: "Raffetto Russo Valeria",},
{value: "http://bit.ly/raimondohernan", label: "Raimondo Hernan", desc: "Raimondo Hernan",},
{value: "http://bit.ly/raimundosebastian", label: "Raimundo Sebastian", desc: "Raimundo Sebastian",},
{value: "http://bit.ly/ramospehoracio", label: "Ramospe Horacio", desc: "Ramospe Horacio",},
{value: "http://bit.ly/ranuamauro", label: "Ranua Mauro", desc: "Ranua Mauro",},
{value: "http://bit.ly/rattmario", label: "Ratt Mario", desc: "Ratt Mario",},
{value: "http://bit.ly/fernandoreynolds", label: "Reynolds Fernando", desc: "Reynolds Fernando",},
{value: "http://bit.ly/riccamaximiliano", label: "Ricca Reitober Maximiliano Joaquin", desc: "Ricca Reitober Maximiliano Joaquin",},
{value: "http://bit.ly/ricettigustavo", label: "Ricetti Gustavo Enrique", desc: "Ricetti Gustavo Enrique",},
{value: "http://bit.ly/richardscarlos", label: "Richards Carlos", desc: "Richards Carlos",},
{value: "http://bit.ly/rioscesar", label: "Rios Cesar", desc: "Rios Cesar",},
{value: "http://bit.ly/robleshector", label: "Robles Héctor", desc: "Robles Héctor",},
{value: "http://bit.ly/rodriguezernesto", label: "Rodriguez Ernesto", desc: "Rodriguez Ernesto",},
{value: "http://bit.ly/rodriguezgoyruben", label: "Rodriguez Goy Ruben", desc: "Rodriguez Goy Ruben",},
{value: "http://bit.ly/rodriguezjavier", label: "Rodriguez Javier", desc: "Rodriguez Javier",},
{value: "http://bit.ly/rodriguezwalter", label: "Rodriguez Walter", desc: "Rodriguez Walter",},
{value: "http://bit.ly/rofelddaniel", label: "Rofeld Daniel", desc: "Rofeld Daniel",},
{value: "http://bit.ly/rolandogabriel", label: "Rolando Gabriel", desc: "Rolando Gabriel",},
{value: "http://bit.ly/rollamatias", label: "Rolla José Matias", desc: "Rolla José Matias",},
{value: "http://bit.ly/romanazziricardo", label: "Romanazzi Ricardo", desc: "Romanazzi Ricardo",},
{value: "http://bit.ly/romerobeatriz", label: "Romero Beatriz", desc: "Romero Beatriz",},
{value: "http://bit.ly/rosascofabio", label: "Rosasco Flavio Alejandro", desc: "Rosasco Flavio Alejandro",},
{value: "http://bit.ly/rosquellasmaria", label: "Rosquellas Maria", desc: "Rosquellas Maria",},
{value: "http://bit.ly/rossinisandra", label: "Rossini Sandra", desc: "Rossini Sandra",},
{value: "http://bit.ly/roviraluis", label: "Rovira Luis", desc: "Rovira Luis",},
{value: "http://bit.ly/rubingustavo", label: "Rubin Gustavo", desc: "Rubin Gustavo",},
{value: "http://bit.ly/sagnesbernardo", label: "Sagnes Bernardo Andres", desc: "Sagnes Bernardo Andres",},
{value: "http://bit.ly/salinasfederico", label: "Salinas Federico Mariano", desc: "Salinas Federico Mariano",},
{value: "http://bit.ly/sanchezhector", label: "Sanchez Héctor Fabio", desc: "Sanchez Héctor Fabio",},
{value: "http://bit.ly/saporitosoledad", label: "Saporito Soledad", desc: "Saporito Soledad",},
{value: "http://bit.ly/saucedojose", label: "Saucedo Aguirre Jose", desc: "Saucedo Aguirre Jose",},
{value: "http://bit.ly/savastanoemilio", label: "Savastano Emilio", desc: "Savastano Emilio",},
{value: "http://bit.ly/savoiavanina", label: "Savoia Vanina", desc: "Savoia Vanina",},
{value: "http://bit.ly/schmidtgabriela", label: "Schmidt, Gabriela Cristina", desc: "Schmidt, Gabriela Cristina",},
{value: "http://bit.ly/scheneidermatias", label: "Schneider Matias David", desc: "Schneider Matias David",},
{value: "http://bit.ly/scoppetalucrecia", label: "Scoppeta Lucrecia", desc: "Scoppeta Lucrecia",},
{value: "http://bit.ly/senatoreadriana", label: "Senatore Adriana", desc: "Senatore Adriana",},
{value: "http://bit.ly/serquellajorge", label: "Serquella Jorge", desc: "Serquella Jorge",},
{value: "http://bit.ly/sotoalejandro", label: "Soto Alejandro", desc: "Soto Alejandro",},
{value: "http://bit.ly/sotoveronica", label: "Soto Veronica", desc: "Soto Veronica",},
{value: "http://bit.ly/soutoroberto", label: "Souto Roberto", desc: "Souto Roberto",},
{value: "http://bit.ly/spinettajorge", label: "Spinetta Jorge", desc: "Spinetta Jorge",},
{value: "http://bit.ly/spinosofabian", label: "Spinoso Fabian", desc: "Spinoso Fabian",},
{value: "http://bit.ly/strficekirene", label: "Strficek Irene", desc: "Strficek Irene",},
{value: "http://bit.ly/suarezsergio", label: "Suarez Sergio Hugo", desc: "Suarez Sergio Hugo",},
{value: "http://bit.ly/zubeldiaenzo", label: "Subeldia Enzo", desc: "Subeldia Enzo",},
{value: "http://bit.ly/tarantinojorge", label: "Tarantino Jorge", desc: "Tarantino Jorge",},
{value: "http://bit.ly/taugabriel", label: "Tau Gabriel", desc: "Tau Gabriel",},
{value: "http://bit.ly/marianotraglio", label: "Traglio Mariano", desc: "Traglio Mariano",},
{value: "http://bit.ly/traversoenrique", label: "Traverso Enrique", desc: "Traverso Enrique",},
{value: "http://bit.ly/traversojulio", label: "Traverso Julio", desc: "Traverso Julio",},
{value: "http://bit.ly/trevisonnoandres", label: "Trevisonno Andres Anibal", desc: "Trevisonno Andres Anibal",},
{value: "http://bit.ly/trostalberto", label: "Trost Alberto", desc: "Trost Alberto",},
{value: "http://bit.ly/trujillotamara", label: "Trujillo Tamara", desc: "Trujillo Tamara",},
{value: "http://bit.ly/ulloahugo", label: "Ulloa Hugo", desc: "Ulloa Hugo",},
{value: "http://bit.ly/urretavizcayajose", label: "Urretavizcaya Jose", desc: "Urretavizcaya Jose",},
{value: "http://bit.ly/valerioguillermo", label: "Valerio Guillermo", desc: "Valerio Guillermo",},
{value: "http://bit.ly/vallejopablo", label: "Vallejo Pablo", desc: "Vallejo Pablo",},
{value: "http://bit.ly/juanvarela", label: "Varela Juan", desc: "Varela Juan",},
{value: "http://bit.ly/vastoandres", label: "Vasto Andres", desc: "Vasto Andres",},
{value: "http://bit.ly/vegahoracio", label: "Vega Horacio", desc: "Vega Horacio",},
{value: "http://bit.ly/velardezgabriela", label: "Velardez Gabriela", desc: "Velardez Gabriela",},
{value: "http://bit.ly/venturajorge", label: "Ventura Jorge", desc: "Ventura Jorge",},
{value: "http://bit.ly/venturimaria", label: "Venturi Maria Julieta", desc: "Venturi Maria Julieta",},
{value: "http://bit.ly/vicenterodrigo", label: "Vicente Rodrigo", desc: "Vicente Rodrigo",},
{value: "http://bit.ly/vidaljorge", label: "Vidal Jorge Elias", desc: "Vidal Jorge Elias",},
{value: "http://bit.ly/viggianooscar", label: "Viggiano Oscar Emmanuel", desc: "Viggiano Oscar Emmanuel",},
{value: "http://bit.ly/villanuevapablo", label: "Villanueva Pablo", desc: "Villanueva Pablo",},
{value: "http://bit.ly/vivaswalter", label: "Vivas Walter", desc: "Vivas Walter",},
{value: "http://bit.ly/ybarradaniel", label: "Ybarra Daniel", desc: "Ybarra Daniel",},
{value: "http://bit.ly/yennerichdamian", label: "Yennerich Damian", desc: "Yennerich Damian",},
{value: "http://bit.ly/zabalalaura", label: "Zabala Laura Ileana", desc: "Zabala Laura Ileana",},
{value: "http://bit.ly/zilleruelogustavo", label: "Zilleruelo Gustavo", desc: "Zilleruelo Gustavo",},
    ];
 
    $( "#project" ).autocomplete({
      minLength: 0,
      source: projects,
      focus: function( event, ui ) {
        $( "#project" ).val( ui.item.desc );
        return false;
      },
      select: function( event, ui ) {
        $( "#project" ).val( ui.item.desc);
        $( "#project-id" ).val( ui.item.value );
        $( "#project-description" ).html( ui.item.value);
        $( "#project-icon" ).attr( "src", "images/" + ui.item.icon );
        ir_a();
        return false;
      }
    })
    .autocomplete( "instance" )._renderItem = function( ul, item ) {
      return $( "<li>" )
//        .append( "<div>" + item.label + "<br>" + item.desc + "</div>" )
        .append( "<div>" + item.desc + "</div>" )
        .appendTo( ul );
    };
  } );

//submit
    function ir_a(){
    var link = null;
    link = document.getElementById("project-id").value;
    window.location.href = "https://" + link;
        };
